version: '3.8'
services:

  db:
    image: mariadb:10.11
    restart: always

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 67b7f471fa16819e
      MYSQL_DATABASE: food-consumer
      MYSQL_USER: food-consumer
      MYSQL_PASSWORD: 67b7f471fa16819e
    volumes:
      - db_data:/var/lib/mysql
      - ./config/database/initdb.d:/docker-entrypoint-initdb.d

  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "3333:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: food-consumer
      PMA_PASSWORD: 67b7f471fa16819e

volumes:
  db_data:
