version: '3.8'
services:
  # db for main application (backend)
  maria-db:
    image: mariadb:10.11
    container_name: maria-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 67b7f471fa16819e
      MYSQL_DATABASE: food-consumer
      MYSQL_USER: root
      MYSQL_PASSWORD: 67b7f471fa16819e
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

  # phpMyAdmin just to check db connection (remove if needed)
  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "3081:80"
    depends_on:
      - maria-db
    environment:
      PMA_HOST: maria-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 67b7f471fa16819e

  # main back application container
  java-backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile
    container_name: java-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria-db

  # js backend (for chat only)
  js-backend:
    build:
      context: ./../js-backend
      dockerfile: Dockerfile
    container_name: js-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - maria-db

volumes:
  dbdata:
  static_value: